defaults:
  - _self_
  - data: deepseek
  - data_mode: forget_retain
  - model: tinyllama
  - model_mode: base_freeze_a
  - unlearn_loss: gd+kl

enable_cbd_dfb: true
cbd_dfb_basis_path: ""
cbd_dfb_eigval_weight: false
cbd_dfb_trust_region: false
cbd_dfb_trust_region_epsilon: 1e-3
cbd_dfb_trust_region_delta: 1e-12
cbd_dfb_project_forget_only: false
enable_gmp: false
gmp_basis_path: ""
gmp_project_forget_only: false

trainer:
  strategy: none
  batch_size: 2
  gradient_accumulation_steps: 4
  max_epochs: 10
  learning_rate: 2e-4
  warmup_ratio: 0.1
  weight_decay: 0.01
  seed: 42
  eval_steps: 1000

project: cbd_dfb_tinyllama_deepseek
name: null
debug: false
resume: false
postfix: ""
base_logdir: null
seed: 42
lora_seed: ${seed}

save_dir: artifacts/outputs/model_dir/
BASELOGDIR: "artifacts/outputs/cbd_dfb_deepseek_log"
OUTPUTMODELDIR: "artifacts/outputs_trained_models/cbd_dfb_tinyllama_deepseek"

hydra:
  run:
    dir: ${BASELOGDIR}/${hydra.job.name}/${hydra.job.override_dirname}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    config:
      override_dirname:
        exclude_keys:
          - cbd_dfb_basis_path
          - enable_cbd_dfb
          - cbd_dfb_eigval_weight
          - cbd_dfb_trust_region
          - cbd_dfb_trust_region_epsilon
          - cbd_dfb_trust_region_delta
          - cbd_dfb_project_forget_only
          - enable_gmp
          - gmp_basis_path
          - gmp_project_forget_only
          - save_dir
          - BASELOGDIR
          - OUTPUTMODELDIR
          - unlearn_loss
          - unlearn_loss.retain_weight
          - unlearn_loss.forget_weight
          - data
          - data.conv_template
          - trainer.batch_size
          - trainer.gradient_accumulation_steps
          - trainer.max_epochs
          - trainer.learning_rate
          - trainer.warmup_ratio
          - trainer.weight_decay
          - trainer.eval_steps
          - model
